---
- name: Déploiement de l'application web
  hosts: all
  become: yes

  vars:
    app_src: "../app"
    app_dest: "/var/www/html/tp-app"
    server_ip: "{{ ansible_host }}"

  tasks:
    - name: Installer Nginx
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Créer le répertoire de destination
      file:
        path: "{{ app_dest }}"
        state: directory
        mode: '0755'

    - name: Copier les fichiers de l'application
      copy:
        src: "{{ app_src }}/"
        dest: "{{ app_dest }}/"
        mode: '0644'

    - name: Copier la configuration Nginx
      template:
        src: "nginx_vhost.conf.j2"
        dest: "/etc/nginx/sites-available/tp-app.conf"

    - name: Activer le virtual host
      file:
        src: "/etc/nginx/sites-available/tp-app.conf"
        dest: "/etc/nginx/sites-enabled/tp-app.conf"
        state: link
        force: yes

    - name: Supprimer la config par défaut de Nginx
      file:
        path: "/etc/nginx/sites-enabled/default"
        state: absent

    - name: Redémarrer Nginx
      service:
        name: nginx
        state: restarted
