name: Basic CI Workflow

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run application check script
        run: ./app/check_app.sh

      - name: Display index.html content
        run: cat ./app/index.html

      - name: Display secrets and environment variables
        env:
          FAKE_API_TOKEN: ${{ secrets.FAKE_API_TOKEN }}
          ENV_TYPE: ${{ secrets.ENV_TYPE }}
          CUSTOM_VAR: "Variable non secrète"
          RUNNER_OS: ${{ runner.os }}
        run: |
          echo "FAKE_API_TOKEN=$FAKE_API_TOKEN"
          echo "ENV_TYPE=$ENV_TYPE"
          echo "CUSTOM_VAR=$CUSTOM_VAR"
          echo "RUNNER_OS=$RUNNER_OS"
