name: Secure CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build-test-security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run application check
        run: ./app/check_app.sh

      - name: CodeQL Security Analysis
        uses: github/codeql-action/init@v3
        with:
          languages: javascript
      - uses: github/codeql-action/analyze@v3

  deploy:
    needs: build-test-security
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Ansible
        run: sudo apt update && sudo apt install -y ansible

      - name: Add SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 192.168.56.10 >> ~/.ssh/known_hosts

      - name: Run Ansible playbook
        run: ansible-playbook -i ansible/hosts ansible/deploy.yml
